services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=TestDB
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/raw-data
    networks:
      - netlink

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code/backend
    depends_on:
      - db
        #condition: service_healthy
        #restart: true
    networks:
      - netlink
     
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - fastapi
        #condition: service_healthy
        #restart: true
    #environment:
    #  - WAIT_HOSTS: fastapi:8000
    networks:
      - netlink
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - netlink

networks:
  netlink:
    driver: bridge
    name: netlink